# Licensed under the Apache License, Version 2.0.

[workspace]
members = [
    "tesseract",
    "errorcon",
    "playground",
    "protocols/substrate",
    "protocols/test"
]

resolver = "2"

[workspace.dependencies]
async-trait = "0.1"
serde = "1.0"
futures = "0.3"
